name: Testing
on: push

jobs:
  test_project:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade 
        pip install -r requirements.txt
    - name: Run unittest
      run: |
        python -m unittest -b
    - name: Upload coverage data to coveralls.io
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github