name: Testing
on: push

jobs:
  test_project:
    # strategy:
    #   matrix:
    #     os: [macos-latest, ubuntu-latest]
    # runs-on: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Run unittest
    #   run: |
    #     python -m unittest -b
    - name: Run tests and collect coverage
      run: |
        python -m pip install coverage
        coverage run -m unittest -b
        coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: MJBishop/im2geojson